### ISSUE TITLE
 Error in v-on handler: "SecurityError: An attempt was made to break through the security policy of the user agent."

### ISSUE THREAD

**Issue by wty302857194** [nicolasbeauvais/vue-social-sharing#355]
Error in v-on handler: "SecurityError: An attempt was made to break through the security policy of the user agent."

**Comment by SylvainLano** [comment]
I just had the same error !

In the console :
reactivity.esm-bundler.js:978 Uncaught DOMException: An attempt was made to break through the security policy of the user agent.
    at isRef (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:950:20)
    at MutableReactiveHandler.get (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:497:9)
    at Object.get (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2749:24)
    at eval (webpack-internal:///./node_modules/vue-social-sharing/dist/vue-social-sharing.js:1844:15)
    
    
On the page itself :
Uncaught runtime errors:
×
ERROR
An attempt was made to break through the security policy of the user agent.
    at isRef (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:950:20)
    at MutableReactiveHandler.get (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:497:9)
    at Object.get (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2749:24)
    at eval (webpack-internal:///./node_modules/vue-social-sharing/dist/vue-social-sharing.js:1844:15)

**Comment by SneyX** [comment]
did you guys were able to fix it?

**Comment by SylvainLano** [comment]
Nope, sorry, and there was no point on modifying the code, so I ended up creating my own social sharing options.
You can see them under the destination name here : https://sylvainlano.github.io/VoyageVue
If it can help, the code of the sharing component in Vue is there (to be adapted to your needs) : https://github.com/SylvainLano/VoyageVue/blob/master/src/components/SharingOptions.vue
It uses a JSON to register the list of social networks and the image to display for them with font-awesome if you're to use it.
