### ISSUE TITLE
VUE2 NUXT vue-social-sharing .   Error : Uncaught DOMException: An attempt was made to break through the security policy of the user agent.

### ISSUE THREAD

**Issue by suangencong** [nicolasbeauvais/vue-social-sharing#362]
Uncaught DOMException: An attempt was made to break through the security policy of the user agent.
    at ie (https://www.XXXX.com/_nuxt/a1925a6.js:2:12130)
    at Object.get [as popupWindow] (https://www.XXXX.com/_nuxt/a1925a6.js:2:10906)
    at vo.get [as popupWindow] (https://www.XXXX.com/_nuxt/a1925a6.js:2:40591)
    at https://www.XXXX.com/_nuxt/dadf402.js:2:64148

**Comment by suangencong** [comment]
Please tell me how to solve this problem. If you know, thank you for your support.

**Comment by arafath** [comment]
Hello @nicolasbeauvais , We are also getting the same issue. Could you please, help! Atleast for starter, giving some insights  on the issue. ?

**Comment by arafath** [comment]
@suangencong : Did you find fix for this ? I am also facing the same problem.

**Comment by alessioacella** [comment]
I am also facing the same problem.
